branches:
  only:
    - master

image:
  - Ubuntu
    
environment:
  MYGET_KEY:
    secure: pV/WNkVHe6bB7G2vnh1O1AoJr0MF7tO8XCr9VNPhXfxGIe7vH2a+HZBtcvIT/fOT

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

test: off